# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "magemods_audio_api"

# Version of this mod.
version = "0.7.2"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Audio API"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
This is an API for modders that enables easily replacing or adding in-game audio.
It supports looped audio, PCM WAV, FLAC, OGG VORBIS, OGG OPUS, and can load these via file path and/or ZIP DMA (influding NRM; ZIP/NRM must be store only without compression!).
Note: This is an fixed and improved version of Magemods Audio API (original: https://github.com/magemods/mm-audio-api).
"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "[BETA] Audio Helper Library"

# Website URL for Thunderstore
website_url = "https://github.com/B3n-17/mm-audio-api"

# Authors of this mod.
authors = [ "magemods", "B3n-17" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.1"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
    { name = "magemods_audio_api", funcs = [
        "AudioApiNative_Init",
        "AudioApiNative_Ready",
        "AudioApiNative_Tick",
        "AudioApiNative_Dma",
        "AudioApiNative_AddResource",
        "AudioApiNative_AddAudioFile",
        "AudioApiNative_AddSampleBank",
    ] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "magemods_audio_api"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = [
    "thumb.dds"
]

# Config options shown in the mod's settings UI.
[[manifest.config_options]]
id = "radio_effect_in_shops"
name = "Radio Effect in Shops"
description = "Applies a band-pass filter and gain to spatial BGM in shops, simulating a radio playing in the room. Takes effect on the next scene change."
type = "Enum"
options = [ "Off", "On" ]
default = "Off"
